name: video_music_app
description: 桌面影音播放器应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  file_picker: ^8.1.2
  video_player: ^2.9.1
  just_audio: ^0.9.40
  shared_preferences: ^2.3.2
  path: ^1.9.0
  crypto: ^3.0.5
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

